{% set name = "so4gp" %}
{% set version = "0.9.3" %}
{% set python_min = "3.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/so4gp-{{ version }}.tar.gz
  sha256: f20917abc776732a7dd1187ed94e27b9d74eca105c04c81e064368882361e58e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=82.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy ==2.4.6
    - pandas ==3.0.3
    - tabulate ==0.10.0
    - scikit-fuzzy ==0.5.0
    - scikit-learn ==1.9.0
    - seaborn ==0.13.2
    - matplotlib-base ==3.11.0
    - python-dateutil ==2.9.0

test:
  imports:
    - so4gp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Some Python optimization algorithms for mining gradual patterns.
  home: https://github.com/owuordickson/sogp_pypi
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owuordickson
